// <auto-generated />
using System;
using AirBB.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBnbContext))]
    partial class AirBnbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AirBB.Models.DomainModels.Client", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DOB = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "owner@airbb.com",
                            Name = "Admin Owner",
                            PhoneNumber = "123-456-7890",
                            UserType = "Owner"
                        },
                        new
                        {
                            UserId = 2,
                            DOB = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "client@airbb.com",
                            Name = "Test Client",
                            PhoneNumber = "987-654-3210",
                            UserType = "Client"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Boston"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Miami"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BathroomNumber")
                        .HasColumnType("REAL");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ResidencePicture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 101,
                            BathroomNumber = 1.0,
                            BedroomNumber = 2,
                            BuiltYear = 2000,
                            GuestNumber = 4,
                            LocationId = 1,
                            Name = "Chicago Loop Apartment",
                            OwnerId = 1,
                            PricePerNight = 189.00m,
                            ResidencePicture = "chi_loop.jpg"
                        },
                        new
                        {
                            ResidenceId = 102,
                            BathroomNumber = 1.0,
                            BedroomNumber = 1,
                            BuiltYear = 1985,
                            GuestNumber = 3,
                            LocationId = 1,
                            Name = "Lincoln Park Flat",
                            OwnerId = 1,
                            PricePerNight = 139.00m,
                            ResidencePicture = "chi_lincoln.jpg"
                        },
                        new
                        {
                            ResidenceId = 201,
                            BathroomNumber = 1.0,
                            BedroomNumber = 1,
                            BuiltYear = 2010,
                            GuestNumber = 2,
                            LocationId = 2,
                            Name = "NYC Soho Loft",
                            OwnerId = 1,
                            PricePerNight = 259.00m,
                            ResidencePicture = "nyc_soho.jpg"
                        },
                        new
                        {
                            ResidenceId = 301,
                            BathroomNumber = 2.0,
                            BedroomNumber = 2,
                            BuiltYear = 1995,
                            GuestNumber = 4,
                            LocationId = 3,
                            Name = "Boston Back Bay Condo",
                            OwnerId = 1,
                            PricePerNight = 209.00m,
                            ResidencePicture = "bos_backbay.jpg"
                        },
                        new
                        {
                            ResidenceId = 401,
                            BathroomNumber = 2.0,
                            BedroomNumber = 3,
                            BuiltYear = 2015,
                            GuestNumber = 6,
                            LocationId = 4,
                            Name = "Miami Beach House",
                            OwnerId = 1,
                            PricePerNight = 299.00m,
                            ResidencePicture = "mia_beach.jpg"
                        });
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Residence", "Residence")
                        .WithMany()
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Residence", b =>
                {
                    b.HasOne("AirBB.Models.DomainModels.Location", "Location")
                        .WithMany("Residences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBB.Models.DomainModels.Client", "Owner")
                        .WithMany("Residences")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Client", b =>
                {
                    b.Navigation("Residences");
                });

            modelBuilder.Entity("AirBB.Models.DomainModels.Location", b =>
                {
                    b.Navigation("Residences");
                });
#pragma warning restore 612, 618
        }
    }
}
